name: example
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pro_image_editor:
    path: ../

  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  google_fonts: ^6.2.1
  image: ^4.2.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  supabase_flutter: ^2.6.0
  image_picker: ^1.1.2
  mime: ^1.0.6
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0

dependency_overrides:
  # Fix conflict between firebase and web package
  web: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/demo.png
    - assets/google_fonts/
